default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  username: postgres
  password: pgadmin
  database: development-ifit

test: &test
  <<: *default
  host: localhost
  username: postgres
  password: pgadmin
  database: test-ifit

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cucumber:
  <<: *test
