default: &default
  adapter: mysql
  pool: 5
  timeout: 5000

development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: development-ifit
  pool: 5
  username: root
  password: 1234
  host: localhost

test: &test
  <<: *default
  host: localhost
  username: root
  password: 1234
  database: test-ifit

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

cucumber:
  <<: *test
