require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DadosCartaosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # DadosCartao. As you add validations to DadosCartao, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DadosCartaosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    xit "assigns all dados_cartaos as @dados_cartaos" do
      dados_cartao = DadosCartao.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:dados_cartaos)).to eq([dados_cartao])
    end
  end

  describe "GET #show" do
    xit "assigns the requested dados_cartao as @dados_cartao" do
      dados_cartao = DadosCartao.create! valid_attributes
      get :show, params: {id: dados_cartao.to_param}, session: valid_session
      expect(assigns(:dados_cartao)).to eq(dados_cartao)
    end
  end

  describe "GET #new" do
    xit "assigns a new dados_cartao as @dados_cartao" do
      get :new, params: {}, session: valid_session
      expect(assigns(:dados_cartao)).to be_a_new(DadosCartao)
    end
  end

  describe "GET #edit" do
    xit "assigns the requested dados_cartao as @dados_cartao" do
      dados_cartao = DadosCartao.create! valid_attributes
      get :edit, params: {id: dados_cartao.to_param}, session: valid_session
      expect(assigns(:dados_cartao)).to eq(dados_cartao)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      xit "creates a new DadosCartao" do
        expect {
          post :create, params: {dados_cartao: valid_attributes}, session: valid_session
        }.to change(DadosCartao, :count).by(1)
      end

      xit "assigns a newly created dados_cartao as @dados_cartao" do
        post :create, params: {dados_cartao: valid_attributes}, session: valid_session
        expect(assigns(:dados_cartao)).to be_a(DadosCartao)
        expect(assigns(:dados_cartao)).to be_persisted
      end

      xit "redirects to the created dados_cartao" do
        post :create, params: {dados_cartao: valid_attributes}, session: valid_session
        expect(response).to redirect_to(DadosCartao.last)
      end
    end

    context "with invalid params" do
      xit "assigns a newly created but unsaved dados_cartao as @dados_cartao" do
        post :create, params: {dados_cartao: invalid_attributes}, session: valid_session
        expect(assigns(:dados_cartao)).to be_a_new(DadosCartao)
      end

      xit "re-renders the 'new' template" do
        post :create, params: {dados_cartao: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      xit "updates the requested dados_cartao" do
        dados_cartao = DadosCartao.create! valid_attributes
        put :update, params: {id: dados_cartao.to_param, dados_cartao: new_attributes}, session: valid_session
        dados_cartao.reload
        skip("Add assertions for updated state")
      end

      xit "assigns the requested dados_cartao as @dados_cartao" do
        dados_cartao = DadosCartao.create! valid_attributes
        put :update, params: {id: dados_cartao.to_param, dados_cartao: valid_attributes}, session: valid_session
        expect(assigns(:dados_cartao)).to eq(dados_cartao)
      end

      xit "redirects to the dados_cartao" do
        dados_cartao = DadosCartao.create! valid_attributes
        put :update, params: {id: dados_cartao.to_param, dados_cartao: valid_attributes}, session: valid_session
        expect(response).to redirect_to(dados_cartao)
      end
    end

    context "with invalid params" do
      xit "assigns the dados_cartao as @dados_cartao" do
        dados_cartao = DadosCartao.create! valid_attributes
        put :update, params: {id: dados_cartao.to_param, dados_cartao: invalid_attributes}, session: valid_session
        expect(assigns(:dados_cartao)).to eq(dados_cartao)
      end

      xit "re-renders the 'edit' template" do
        dados_cartao = DadosCartao.create! valid_attributes
        put :update, params: {id: dados_cartao.to_param, dados_cartao: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    xit "destroys the requested dados_cartao" do
      dados_cartao = DadosCartao.create! valid_attributes
      expect {
        delete :destroy, params: {id: dados_cartao.to_param}, session: valid_session
      }.to change(DadosCartao, :count).by(-1)
    end

    xit "redirects to the dados_cartaos list" do
      dados_cartao = DadosCartao.create! valid_attributes
      delete :destroy, params: {id: dados_cartao.to_param}, session: valid_session
      expect(response).to redirect_to(dados_cartaos_url)
    end
  end

end
