require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe EnderecoRestaurantesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # EnderecoRestaurante. As you add validations to EnderecoRestaurante, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EnderecoRestaurantesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all endereco_restaurantes as @endereco_restaurantes" do
      endereco_restaurante = EnderecoRestaurante.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:endereco_restaurantes)).to eq([endereco_restaurante])
    end
  end

  describe "GET #show" do
    it "assigns the requested endereco_restaurante as @endereco_restaurante" do
      endereco_restaurante = EnderecoRestaurante.create! valid_attributes
      get :show, params: {id: endereco_restaurante.to_param}, session: valid_session
      expect(assigns(:endereco_restaurante)).to eq(endereco_restaurante)
    end
  end

  describe "GET #new" do
    it "assigns a new endereco_restaurante as @endereco_restaurante" do
      get :new, params: {}, session: valid_session
      expect(assigns(:endereco_restaurante)).to be_a_new(EnderecoRestaurante)
    end
  end

  describe "GET #edit" do
    it "assigns the requested endereco_restaurante as @endereco_restaurante" do
      endereco_restaurante = EnderecoRestaurante.create! valid_attributes
      get :edit, params: {id: endereco_restaurante.to_param}, session: valid_session
      expect(assigns(:endereco_restaurante)).to eq(endereco_restaurante)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new EnderecoRestaurante" do
        expect {
          post :create, params: {endereco_restaurante: valid_attributes}, session: valid_session
        }.to change(EnderecoRestaurante, :count).by(1)
      end

      it "assigns a newly created endereco_restaurante as @endereco_restaurante" do
        post :create, params: {endereco_restaurante: valid_attributes}, session: valid_session
        expect(assigns(:endereco_restaurante)).to be_a(EnderecoRestaurante)
        expect(assigns(:endereco_restaurante)).to be_persisted
      end

      it "redirects to the created endereco_restaurante" do
        post :create, params: {endereco_restaurante: valid_attributes}, session: valid_session
        expect(response).to redirect_to(EnderecoRestaurante.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved endereco_restaurante as @endereco_restaurante" do
        post :create, params: {endereco_restaurante: invalid_attributes}, session: valid_session
        expect(assigns(:endereco_restaurante)).to be_a_new(EnderecoRestaurante)
      end

      it "re-renders the 'new' template" do
        post :create, params: {endereco_restaurante: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested endereco_restaurante" do
        endereco_restaurante = EnderecoRestaurante.create! valid_attributes
        put :update, params: {id: endereco_restaurante.to_param, endereco_restaurante: new_attributes}, session: valid_session
        endereco_restaurante.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested endereco_restaurante as @endereco_restaurante" do
        endereco_restaurante = EnderecoRestaurante.create! valid_attributes
        put :update, params: {id: endereco_restaurante.to_param, endereco_restaurante: valid_attributes}, session: valid_session
        expect(assigns(:endereco_restaurante)).to eq(endereco_restaurante)
      end

      it "redirects to the endereco_restaurante" do
        endereco_restaurante = EnderecoRestaurante.create! valid_attributes
        put :update, params: {id: endereco_restaurante.to_param, endereco_restaurante: valid_attributes}, session: valid_session
        expect(response).to redirect_to(endereco_restaurante)
      end
    end

    context "with invalid params" do
      it "assigns the endereco_restaurante as @endereco_restaurante" do
        endereco_restaurante = EnderecoRestaurante.create! valid_attributes
        put :update, params: {id: endereco_restaurante.to_param, endereco_restaurante: invalid_attributes}, session: valid_session
        expect(assigns(:endereco_restaurante)).to eq(endereco_restaurante)
      end

      it "re-renders the 'edit' template" do
        endereco_restaurante = EnderecoRestaurante.create! valid_attributes
        put :update, params: {id: endereco_restaurante.to_param, endereco_restaurante: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested endereco_restaurante" do
      endereco_restaurante = EnderecoRestaurante.create! valid_attributes
      expect {
        delete :destroy, params: {id: endereco_restaurante.to_param}, session: valid_session
      }.to change(EnderecoRestaurante, :count).by(-1)
    end

    it "redirects to the endereco_restaurantes list" do
      endereco_restaurante = EnderecoRestaurante.create! valid_attributes
      delete :destroy, params: {id: endereco_restaurante.to_param}, session: valid_session
      expect(response).to redirect_to(endereco_restaurantes_url)
    end
  end

end
