require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe PagamentoAceitosController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PagamentoAceito. As you add validations to PagamentoAceito, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PagamentoAceitosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    xit "assigns all pagamento_aceitos as @pagamento_aceitos" do
      pagamento_aceito = PagamentoAceito.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:pagamento_aceitos)).to eq([pagamento_aceito])
    end
  end

  describe "GET #show" do
    xit "assigns the requested pagamento_aceito as @pagamento_aceito" do
      pagamento_aceito = PagamentoAceito.create! valid_attributes
      get :show, params: {id: pagamento_aceito.to_param}, session: valid_session
      expect(assigns(:pagamento_aceito)).to eq(pagamento_aceito)
    end
  end

  describe "GET #new" do
    xit "assigns a new pagamento_aceito as @pagamento_aceito" do
      get :new, params: {}, session: valid_session
      expect(assigns(:pagamento_aceito)).to be_a_new(PagamentoAceito)
    end
  end

  describe "GET #edit" do
    xit "assigns the requested pagamento_aceito as @pagamento_aceito" do
      pagamento_aceito = PagamentoAceito.create! valid_attributes
      get :edit, params: {id: pagamento_aceito.to_param}, session: valid_session
      expect(assigns(:pagamento_aceito)).to eq(pagamento_aceito)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      xit "creates a new PagamentoAceito" do
        expect {
          post :create, params: {pagamento_aceito: valid_attributes}, session: valid_session
        }.to change(PagamentoAceito, :count).by(1)
      end

      xit "assigns a newly created pagamento_aceito as @pagamento_aceito" do
        post :create, params: {pagamento_aceito: valid_attributes}, session: valid_session
        expect(assigns(:pagamento_aceito)).to be_a(PagamentoAceito)
        expect(assigns(:pagamento_aceito)).to be_persisted
      end

      xit "redirects to the created pagamento_aceito" do
        post :create, params: {pagamento_aceito: valid_attributes}, session: valid_session
        expect(response).to redirect_to(PagamentoAceito.last)
      end
    end

    context "with invalid params" do
      xit "assigns a newly created but unsaved pagamento_aceito as @pagamento_aceito" do
        post :create, params: {pagamento_aceito: invalid_attributes}, session: valid_session
        expect(assigns(:pagamento_aceito)).to be_a_new(PagamentoAceito)
      end

      xit "re-renders the 'new' template" do
        post :create, params: {pagamento_aceito: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      xit "updates the requested pagamento_aceito" do
        pagamento_aceito = PagamentoAceito.create! valid_attributes
        put :update, params: {id: pagamento_aceito.to_param, pagamento_aceito: new_attributes}, session: valid_session
        pagamento_aceito.reload
        skip("Add assertions for updated state")
      end

      xit "assigns the requested pagamento_aceito as @pagamento_aceito" do
        pagamento_aceito = PagamentoAceito.create! valid_attributes
        put :update, params: {id: pagamento_aceito.to_param, pagamento_aceito: valid_attributes}, session: valid_session
        expect(assigns(:pagamento_aceito)).to eq(pagamento_aceito)
      end

      xit "redirects to the pagamento_aceito" do
        pagamento_aceito = PagamentoAceito.create! valid_attributes
        put :update, params: {id: pagamento_aceito.to_param, pagamento_aceito: valid_attributes}, session: valid_session
        expect(response).to redirect_to(pagamento_aceito)
      end
    end

    context "with invalid params" do
      xit "assigns the pagamento_aceito as @pagamento_aceito" do
        pagamento_aceito = PagamentoAceito.create! valid_attributes
        put :update, params: {id: pagamento_aceito.to_param, pagamento_aceito: invalid_attributes}, session: valid_session
        expect(assigns(:pagamento_aceito)).to eq(pagamento_aceito)
      end

      xit "re-renders the 'edit' template" do
        pagamento_aceito = PagamentoAceito.create! valid_attributes
        put :update, params: {id: pagamento_aceito.to_param, pagamento_aceito: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    xit "destroys the requested pagamento_aceito" do
      pagamento_aceito = PagamentoAceito.create! valid_attributes
      expect {
        delete :destroy, params: {id: pagamento_aceito.to_param}, session: valid_session
      }.to change(PagamentoAceito, :count).by(-1)
    end

    xit "redirects to the pagamento_aceitos list" do
      pagamento_aceito = PagamentoAceito.create! valid_attributes
      delete :destroy, params: {id: pagamento_aceito.to_param}, session: valid_session
      expect(response).to redirect_to(pagamento_aceitos_url)
    end
  end

end
